export const messageOrder = {
  ORDER_CONFIRM: 'Đã xác nhận đơn hàng',
  ORDER_PEDDING: 'Đang giao',
  ORDER_SUCESS: 'Giao hàng thành công',
  ORDER_WAIT_CONFIRM: 'Chờ xác nhận',
  ORDER_FAILED: 'Giao hàng thất bại',
  WRONG_USER_INFORMATION: 'Đặt hàng thất bại thông tin khách hàng chưa chính xác',
  CANCEL_ORDER: 'Đã hủy',
  ORDER_CONFIRM_FAIL_2: 'Giao hàng thất bại không thể liên lạc với người nhận',
  ORDER_CONFIRM_FAIL_1: 'Giao hàng thất bại người nhận từ chối nhận hàng',
  ORDER_CONFIRM_FAIL: 'Sản phẩm tạm hết hàng',
  USER_CANCEL_ORDER: 'Khách hàng đã hủy',
  CANCEL_ORDER_FAIL: 'Đơn hàng đang được giao và không thể hủy.',
  USER_RETURN_ORDER: 'Khách hàng trả hàng',
  USER_CANCEL_RETURN_ORDER: 'Hủy hoàn hàng',
  RETURN_ORDER_SUCCESS: 'Trả hàng thành công',
  RETURN_ORDER_FAIL: 'Trả hàng thất bại',
  RETURN_ORDER_WAIT_CONFIRM: 'Đang kiểm tra hàng',
  REUTRN_ORDER_CONFIRM: 'Đã xác nhận trả hàng'
}
